<?php

namespace ContainerQqapKk1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RiXx_PiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RiXx.pi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RiXx.pi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.n0rHgVf.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator.n0rHgVf.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\AuthController::guest' => ['privates', '.service_locator.n0rHgVf.App\\Controller\\AuthController::guest()', 'getAuthControllerguestService', true],
            'App\\Controller\\FavoriteLocationController::list' => ['privates', '.service_locator.LofviEd.App\\Controller\\FavoriteLocationController::list()', 'getFavoriteLocationControllerlistService', true],
            'App\\Controller\\FavoriteLocationController::add' => ['privates', '.service_locator.TEs8Woo.App\\Controller\\FavoriteLocationController::add()', 'getFavoriteLocationControlleraddService', true],
            'App\\Controller\\FavoriteLocationController::remove' => ['privates', '.service_locator.ICsE.Iz.App\\Controller\\FavoriteLocationController::remove()', 'getFavoriteLocationControllerremoveService', true],
            'App\\Controller\\FavoritePoiController::list' => ['privates', '.service_locator.fB1cJ6X.App\\Controller\\FavoritePoiController::list()', 'getFavoritePoiControllerlistService', true],
            'App\\Controller\\FavoritePoiController::add' => ['privates', '.service_locator.CjUwthi.App\\Controller\\FavoritePoiController::add()', 'getFavoritePoiControlleraddService', true],
            'App\\Controller\\FavoritePoiController::remove' => ['privates', '.service_locator.0M4b.J7.App\\Controller\\FavoritePoiController::remove()', 'getFavoritePoiControllerremoveService', true],
            'App\\Controller\\LocationController::nearby' => ['privates', '.service_locator.TecBZ6u.App\\Controller\\LocationController::nearby()', 'getLocationControllernearbyService', true],
            'App\\Controller\\PoiController::list' => ['privates', '.service_locator.VVF_sGi.App\\Controller\\PoiController::list()', 'getPoiControllerlistService', true],
            'App\\Controller\\UserController::updateMe' => ['privates', '.service_locator.lQAlGdR.App\\Controller\\UserController::updateMe()', 'getUserControllerupdateMeService', true],
            'App\\Controller\\UserController::deleteMe' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UserController::deleteMe()', 'getUserControllerdeleteMeService', true],
            'App\\Controller\\UserController::testLocation' => ['privates', '.service_locator.TecBZ6u.App\\Controller\\UserController::testLocation()', 'getUserControllertestLocationService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.n0rHgVf.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator.n0rHgVf.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\AuthController:guest' => ['privates', '.service_locator.n0rHgVf.App\\Controller\\AuthController::guest()', 'getAuthControllerguestService', true],
            'App\\Controller\\FavoriteLocationController:list' => ['privates', '.service_locator.LofviEd.App\\Controller\\FavoriteLocationController::list()', 'getFavoriteLocationControllerlistService', true],
            'App\\Controller\\FavoriteLocationController:add' => ['privates', '.service_locator.TEs8Woo.App\\Controller\\FavoriteLocationController::add()', 'getFavoriteLocationControlleraddService', true],
            'App\\Controller\\FavoriteLocationController:remove' => ['privates', '.service_locator.ICsE.Iz.App\\Controller\\FavoriteLocationController::remove()', 'getFavoriteLocationControllerremoveService', true],
            'App\\Controller\\FavoritePoiController:list' => ['privates', '.service_locator.fB1cJ6X.App\\Controller\\FavoritePoiController::list()', 'getFavoritePoiControllerlistService', true],
            'App\\Controller\\FavoritePoiController:add' => ['privates', '.service_locator.CjUwthi.App\\Controller\\FavoritePoiController::add()', 'getFavoritePoiControlleraddService', true],
            'App\\Controller\\FavoritePoiController:remove' => ['privates', '.service_locator.0M4b.J7.App\\Controller\\FavoritePoiController::remove()', 'getFavoritePoiControllerremoveService', true],
            'App\\Controller\\LocationController:nearby' => ['privates', '.service_locator.TecBZ6u.App\\Controller\\LocationController::nearby()', 'getLocationControllernearbyService', true],
            'App\\Controller\\PoiController:list' => ['privates', '.service_locator.VVF_sGi.App\\Controller\\PoiController::list()', 'getPoiControllerlistService', true],
            'App\\Controller\\UserController:updateMe' => ['privates', '.service_locator.lQAlGdR.App\\Controller\\UserController::updateMe()', 'getUserControllerupdateMeService', true],
            'App\\Controller\\UserController:deleteMe' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UserController::deleteMe()', 'getUserControllerdeleteMeService', true],
            'App\\Controller\\UserController:testLocation' => ['privates', '.service_locator.TecBZ6u.App\\Controller\\UserController::testLocation()', 'getUserControllertestLocationService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\AuthController::login' => '?',
            'App\\Controller\\AuthController::guest' => '?',
            'App\\Controller\\FavoriteLocationController::list' => '?',
            'App\\Controller\\FavoriteLocationController::add' => '?',
            'App\\Controller\\FavoriteLocationController::remove' => '?',
            'App\\Controller\\FavoritePoiController::list' => '?',
            'App\\Controller\\FavoritePoiController::add' => '?',
            'App\\Controller\\FavoritePoiController::remove' => '?',
            'App\\Controller\\LocationController::nearby' => '?',
            'App\\Controller\\PoiController::list' => '?',
            'App\\Controller\\UserController::updateMe' => '?',
            'App\\Controller\\UserController::deleteMe' => '?',
            'App\\Controller\\UserController::testLocation' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\AuthController:login' => '?',
            'App\\Controller\\AuthController:guest' => '?',
            'App\\Controller\\FavoriteLocationController:list' => '?',
            'App\\Controller\\FavoriteLocationController:add' => '?',
            'App\\Controller\\FavoriteLocationController:remove' => '?',
            'App\\Controller\\FavoritePoiController:list' => '?',
            'App\\Controller\\FavoritePoiController:add' => '?',
            'App\\Controller\\FavoritePoiController:remove' => '?',
            'App\\Controller\\LocationController:nearby' => '?',
            'App\\Controller\\PoiController:list' => '?',
            'App\\Controller\\UserController:updateMe' => '?',
            'App\\Controller\\UserController:deleteMe' => '?',
            'App\\Controller\\UserController:testLocation' => '?',
        ]);
    }
}
