<?php

namespace ContainerQqapKk1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n0rHgVf.App\Controller\AuthController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n0rHgVf.App\\Controller\\AuthController::register()'] = ($container->privates['.service_locator.n0rHgVf'] ?? $container->load('get_ServiceLocator_N0rHgVfService'))->withContext('App\\Controller\\AuthController::register()', $container);
    }
}
