<?php

namespace ContainerQqapKk1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoritePoiControllerremoveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0M4b.J7.App\Controller\FavoritePoiController::remove()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0M4b.J7.App\\Controller\\FavoritePoiController::remove()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\FavoritePoiRepository', 'getFavoritePoiRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'repo' => 'App\\Repository\\FavoritePoiRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\FavoritePoiController::remove()', $container);
    }
}
