<?php

namespace ContainerQqapKk1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoriteLocationControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LofviEd.App\Controller\FavoriteLocationController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LofviEd.App\\Controller\\FavoriteLocationController::list()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\FavoriteLocationRepository', 'getFavoriteLocationRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\FavoriteLocationRepository',
        ]))->withContext('App\\Controller\\FavoriteLocationController::list()', $container);
    }
}
