<?php

namespace ContainerQqapKk1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationControllernearbyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TecBZ6u.App\Controller\LocationController::nearby()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TecBZ6u.App\\Controller\\LocationController::nearby()'] = ($container->privates['.service_locator.TecBZ6u'] ?? $container->load('get_ServiceLocator_TecBZ6uService'))->withContext('App\\Controller\\LocationController::nearby()', $container);
    }
}
