<?php

namespace ContainerQqapKk1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPoiControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VVF_sGi.App\Controller\PoiController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VVF_sGi.App\\Controller\\PoiController::list()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\PoiRepository', 'getPoiRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\PoiRepository',
        ]))->withContext('App\\Controller\\PoiController::list()', $container);
    }
}
