<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQqapKk1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQqapKk1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQqapKk1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQqapKk1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQqapKk1\App_KernelDevDebugContainer([
    'container.build_hash' => 'QqapKk1',
    'container.build_id' => '06a0ba68',
    'container.build_time' => 1753378670,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQqapKk1');
